### ISSUE TITLE
which version of the SOEM library is binding?

### ISSUE THREAD

**Issue by jackie-wayland** [bnjmnp/pysoem#19]

**Comment by bnjmnp** [comment]
Hi @jackie-wayland,

I am not sure if binding is the correct terminology, because the SOEM library is directly compiled into a Python extension.
Anyway, the current PySOEM version (0.1.1) is based on SOEMs release version v1.4.0 but also incorporates some later commits. If you like to know exactly, take a look at the [SOEM network graph](https://github.com/OpenEtherCATsociety/SOEM/network), I have merged the commit from the 3th March 2020 into my fork.
For the future I could try to use only exact release versions, but there are no frequent SOEM releases.
